### ISSUE TITLE
Track overlaps and skater goes in front of energy graph 

### ISSUE THREAD

**Issue by jaspearias** [phetsims/energy-skate-park#110]
<b>Test Device</b>

Hanson

<b>Operating System</b>

Windows 10

<b>Browser</b>

Internet Explorer

<b>Problem Description</b>

For https://github.com/phetsims/QA/issues/397
In the Lab screen when customizing your own track the track overlaps the box with the friction/mass/gravity sliders. The track also goes behind the energy graph but the the skater stays in front of it.

<b>Visuals</b>

https://drive.google.com/file/d/1SYx1Yes9uWHE8j_dgIaf68C4pbWpc732/view?usp=sharing

**Comment by arouinfar** [comment]
Good find @jaspearias. 

@jessegreenberg I think the tracks and skater should be layered above everything, including the bar graph.

This behavior would be fairly consistent with the published version of ESPB, though the z-ordering of the Bar Graph is a bit wonky there. (It also predates the griddle work.)
![image](https://user-images.githubusercontent.com/8419308/64049786-32f1f880-cb33-11e9-9825-5ee755380402.png)

**Comment by jessegreenberg** [comment]
The layering of the sim as it is in the published version was a previous requirement of using WebGL. But now that we are no longer using WebGL, we should be able to layer however we wish! I will move the tracks and skater above everything.

**Comment by jessegreenberg** [comment]
OK, the layering has been changed so that the skater and tracks are above all non-interactive components. For the measure screen, the layering order is
- tracks
- skater path
- skater path sensor
- measuring tape
- skater

so that the measuring tape cannot get hidden behind the skater path sensor and the sensor and skater look good on top of the measurable skater path. Closing.
