### ISSUE TITLE
Color of the measureing tape readout

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/energy-skate-park#142]
I find it a bit hard to see the white value readout on the light blue sky. Just thought I would point it out to @arouinfar, what do you think?

**Comment by arouinfar** [comment]
@jessegreenberg let's make the text black and add a transparent white rectangle behind the readout. We did this in Wave Interference, and the string stays readable.
![image](https://user-images.githubusercontent.com/8419308/68807970-150e3d00-0626-11ea-8e93-0a68fcb9f247.png)

Also, I think we could use "m" instead of "meters" to tighten up the string a bit.

**Comment by jessegreenberg** [comment]
Done above. We also changed the units to readout 'm' instead of 'meters'.,
