### ISSUE TITLE
use PhetColorScheme.RED_COLORBLIND ?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/energy-skate-park#157]
Several UI elements here that are currently 'red' and therefore not colorblind friendly: control points for track, position 'dot' for the skater, needle on the gauge, ...  Should any of these be PhetColorScheme.RED_COLORBLIND ?

**Comment by jessegreenberg** [comment]
Reviewed colors with @arouinfar -

The thermal energy is represented by PhetColorScheme.RED_COLORBLIND and that is important because it is used in combination with other bright colors.

The other usages of 'red' are for the skater "point mass" and the track control points which are in isolation and look best as they are.

Closing.
