### ISSUE TITLE
Improve the look of the clear thermal buttons

### ISSUE THREAD

**Issue by samreid** [phetsims/energy-skate-park#158]
See https://github.com/phetsims/sun/issues/100, specifically:

> One more thing, in my opinion, these 3d buttons look much nicer (more buttony and consistent with the rest of the sim), so I'm going to create an issue to use the 3d appearance strategy in ESPB now that performance seems good.

**Comment by jessegreenberg** [comment]
@samreid @arouinfar what are your thoughts on this now, do you still think it would be an improvement? This button now exists in scenery-phet with default appearance strategy `RectangularButtonView.FlatAppearanceStrategy` so it seems this button is generally flat now. If we do change for this sim, should it be changed for all sims?

**Comment by samreid** [comment]
The clear thermal button in the sim looks nice to me, but I'm wondering if a designer could comment on the "3d" zoom buttons next to the "flat" clear thermal button:

![image](https://user-images.githubusercontent.com/679486/71193909-2ca19c80-2248-11ea-8762-6da6fcb1e7e5.png)

Should these looks be unified?

**Comment by samreid** [comment]
Also, does the "clear thermal" button look kind of "grayed out" to you?

**Comment by jessegreenberg** [comment]
@arouinfar and I met for this issue - 

We tried a flat appearance strategy for the zoom buttons, but care for the appearance.
![image](https://user-images.githubusercontent.com/6396244/71214818-1a455400-2284-11ea-88fd-4f404a89a1e0.png)

@arouinfar is OK with the difference in appearance strategy for these buttons because we want the zoom buttons to appear more attractive as they are more important for use than the "clear thermal energy" button.

When the button is used in context with its "disabled" state, the "enabled" state also pops out enough so we are happy with its current coloring.

CLosing this issue.
