### ISSUE TITLE
Skater can fall through track when dropped from high up

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/energy-skate-park#159]
At master (891f0d468c3ed6f7f284c46fc023f0b0576e5f26), produced on Chrome OS X.

Skater was dropped from high up, then went through the track to the ground (quite close):

![screen shot 2014-09-26 at 6 05 19 pm](https://cloud.githubusercontent.com/assets/480878/4429062/1ea6251a-45da-11e4-836b-6c4cfd24e877.png)

Incidentally, it was enough energy to have the pie chart cover the skater's head.

**Comment by jessegreenberg** [comment]
https://github.com/phetsims/energy-skate-park-basics/issues/369 may have additional information about this, but https://github.com/phetsims/energy-skate-park/issues/159#issuecomment-57089706 was also suggested there as the reason and it seems like that is likely.

**Comment by jessegreenberg** [comment]
Ill investigate this, it may be a straight forward fix if https://github.com/phetsims/energy-skate-park/issues/159#issuecomment-57089706 is correct.

**Comment by jessegreenberg** [comment]
I confirmed that in this  case the skater has passed through the track and hit the ground in the same step with `EnergySkateParkModel.stepFreeFall`.  It seems like the fix is to check for track collision before  checking for collision with ground.  And this feels safe because all track points should be above ground.

**Comment by jessegreenberg** [comment]
Fixed by the above commit. The skater switches to ground only if it has not crossed  a track in the same  step during `stepFreeFall`. Closing.
