### ISSUE TITLE
Pie & Bar charts should show a minimum amount of energy.

### ISSUE THREAD

**Issue by samreid** [phetsims/energy-skate-park#160]
It is possible to set up the skater to be moving, but the pie chart is showing only thermal energy.  Likewise, the skater can be moving (slowly) and the bar chart doesn't show any kinetic energy.  In the case of a slowly moving skater, or a skater that is even a little bit off the ground, the bars + pie slices should show something.

We previously did other work to _add_ a threshold to the pie chart and bar chart, though I cannot recall why.  Perhaps working on this will reveal the reason!

**Comment by jessegreenberg** [comment]
I will take a look at this issue for the publication of energy-skate-park.

**Comment by jessegreenberg** [comment]
I am not sure how to go about fixing this. This is happening because we have conflicting pedagogical goals.

One goal is listed in https://github.com/phetsims/energy-skate-park/issues/160#issuecomment-62419815, when the skater is moving very slowly we want the kinetic energy to appear zero because we want to convey "The kinetic energy is zero at the top of the trajectory (turning point)".

But this creates cases like https://github.com/phetsims/energy-skate-park/issues/160#issuecomment-62502109 when the skater is moving at low speed anywhere other than turning points. We have a skater in motion while kinetic energy is shown as zero on the graph.

I can't think of a way to support both cases. @arouinfar do you have any ideas for this issue? I am wondering if we should leave the sim as-is if  we have not received any complaints about this since energy-skate-park-basics was deployed. Or we could remove the thresholds that hide small energy bars around trajectory end points so that energy is consistently displayed whenever it is non-zero. However, current behavior has been tested and  we may introduce new issues by doing that.

**Comment by arouinfar** [comment]
@jessegreenberg I am hesitant to make any changes. If I recreate the scenario in https://github.com/phetsims/energy-skate-park/issues/160#issuecomment-62502109 in energy-skate-park and zoom all the way in, there is a non-zero KE bar. However, it is a bit jumpy due to the threshold. Similarly, https://github.com/phetsims/energy-skate-park/issues/160#issuecomment-404880091 is a bit tricky to reproduce -- the track really needs to be nearly vertical for the final velocity to be low enough that the KE bar doesn't appear.

@ariel-phet can you review and advise?

**Comment by ariel-phet** [comment]
@jessegreenberg @arouinfar I agree the thresholds should not be adjusted and the sim has been very successful without concerns from users. 

However, if we wanted to address this concern, one avenue we could consider is to include the measure tool on the Lab screen. That way the kinetic energy value could be displayed and seen to be nonzero. I am not sure if that is a complication we want to add, however, our "Lab" screens do oftne include multiple tools. If I did include that feature, I would just have a checkbox. If you check it the measure tool would appear along with the path.

But if we feel that is too much for the Lab screen, I think this issue could be safely closed.

**Comment by jessegreenberg** [comment]
3/5/20 - We decided to reduce the threshold for when the kinetic and potential energies are fully hidden to make it more difficult to encounter cases like the ones pointed out in this issue.

**Comment by jessegreenberg** [comment]
Done in above commit, this can be closed again.
