### ISSUE TITLE
Use visibleBoundsProperty for managing the floating layout

### ISSUE THREAD

**Issue by samreid** [phetsims/energy-skate-park#163]
From our meeting today:

✓AP: general strategies for floating control panels, eg bending-light.FloatingLayout.
SR: ScreenView.js recently picked up a new property called ScreenView.visibleBoundsProperty, which can be used to position objects inside the visible area.  Simpler than bending light’s floating layout would be to link to that property and position components accordingly.  CCK demonstrates this pattern in 10 places, seach for “visibleBoundsProperty.link”
SR: ExpressionExchange is using this.visibleBoundsProperty.link in ExpressionManipulationView.js line 446

**Comment by jessegreenberg** [comment]
Currently float and other layout is being done in the overridden`layout` function of EnergySkateParkScreenView. So one way to align with strategies used in CCK and others would be to take work out of `layout` function and distribute to various components by passing them the `visibleBoundsProperty`.

**Comment by jessegreenberg** [comment]
Done with the above commits. The work for floating components has been moved out of `layout` and linked to `ScreenView.visibleBoundsProperty`. I think this distributes the work well.
- `layout` - responsible for custom positioning of the EnergySkateParkScreenView so that content is fixed to the navigation bar to create more vertical space where possible
- `floatInterface` - responsible for positioning UI components when there is extra available horizontal space, to be overridden by subtypes when there are unique screen components
- Additional misc tasks in the ScreenView.visibleBoundsProperty callback

Closing.
