### ISSUE TITLE
Measurement tool and path checkbox might need stronger UX coupling

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/energy-skate-park#176]
In playing a bit with https://phet-dev.colorado.edu/html/energy-skate-park/1.0.0-dev.6/phet/energy-skate-park_all_phet.html

I noticed on the measure screen that without the "Path" option checked, the energy measurement tool is basically useless.

A few considerations:

1. Do we need the "Path" checkbox even? What is the point of being on this screen without the path active?

2. If the "Path" is not checked, should the Energy measurement tool disappear as well? If the path is turned off, the tool basically becomes function-less.

3. Do we need stronger cueing that cross hairs of the Energy measurement tool should be put on the path dots?

**Comment by arouinfar** [comment]
> Do we need the "Path" checkbox even? What is the point of being on this screen without the path active?

No, the Path checkbox is definitely not necessary on the Measure screen. I think it was a leftover feature of an earlier scaffolding/screen arrangement. I think we could get rid of it on Measure.

I do wonder if it would be helpful to include the Path checkbox on the Intro and/or Lab screens though, because it nicely shows how the speed changes throughout the track. I don't think it's absolutely necessary, but might be nice. 

> If the "Path" is not checked, should the Energy measurement tool disappear as well? If the path is turned off, the tool basically becomes function-less.

The UX would be really odd to have the tool out in the play area with the Path off. The central goal of this screen is to measure the data along the track, so I would rather just make the Path always on and get rid of the checkbox.

> Do we need stronger cueing that cross hairs of the Energy measurement tool should be put on the path dots?

Possibly. I believe you had suggested to changing the color of the ProbeNode to match the color of the dots. I updated the color of the ProbeNode to match the path dots and played with it locally. @ariel-phet if you would like to do the same, swap out this section of the code in [SkaterPathSensorNode.js](https://github.com/phetsims/energy-skate-park/blob/master/js/energy-skate-park/measure/view/SkaterPathSensorNode.js)

```js
    // the probe
    this.probeNode = new ProbeNode( {
      scale: 0.40,
      rotation: Math.PI / 2,
      sensorTypeFunction: ProbeNode.crosshairs(),
      center: modelViewTransform.modelToViewPosition( sensorProbePositionProperty.get() ),
      cursor: 'pointer',
      color: EnergySkateParkColorScheme.pathFill
    } );
```
Here are few screenshots
![image](https://user-images.githubusercontent.com/8419308/76471589-aa44f680-63b8-11ea-995e-686ee9359ead.png)
![image](https://user-images.githubusercontent.com/8419308/76471379-14a96700-63b8-11ea-9ad7-5089e18ce141.png)

I don't love having different colors for the tool's body and probe, but I think matching the color of the dots does improve the cueing. If we want to go crazy, we could make the entire tool match the color the dots, but I don't particularly like this direction.
![image](https://user-images.githubusercontent.com/8419308/76471882-8c2bc600-63b9-11ea-9f39-507df0a165cd.png)

**Comment by ariel-phet** [comment]
@arouinfar 

1. I like the idea of having the probe color match, but I agree, the whole body matching is a bit much

2. I think having the path always on for that screen and getting rid of the checkbox is a good idea

3. As for having the path checkbox available on the intro or Lab screen is probably good to include @kathy-phet as a question. The lab screen could get difficult, as some pretty whacky tracks can be made. But I would be fine with it on the intro screen.

**Comment by arouinfar** [comment]
Thanks for the feedback @ariel-phet.

@kathy-phet can you take a look at this issue and let me know your thoughts?

**Comment by arouinfar** [comment]
Kathy and I discussed this some, and we thought it would be nice to add the Path feature to Intro and Playground. Tagging for further discussion at tomorrow's design meeting.

**Comment by arouinfar** [comment]
4/23/20 design meeting notes

* Remove Path checkbox from Measure
* Add Path checkbox to Intro screen between Speed and Stick to Track. 
* Don't add Path to the Playground screen. The tracks are more complex, and the goals are served by the static tracks on Intro. We may reconsider if it becomes a common user request.
* Try making the tool body a darker version of `EnergySkateParkColorScheme.pathFill`.

Self-assigning for mockups.

**Comment by arouinfar** [comment]
In design meeting, we decided to explore using a darker shade of the `pathFill` for the tool body. If we go two shades darker, the contrast ratio of the white text against the tool body color is ~7:1.  I've mocked up a few variations.

(1) Probe matches path fill, body 2 shades darker.
![image](https://user-images.githubusercontent.com/8419308/80431430-ac064300-88ae-11ea-973a-cdbef85b3d4b.png)
![Energy Skate Park screenshot (4)](https://user-images.githubusercontent.com/8419308/80431960-2388a200-88b0-11ea-9d7b-2f1c0ff49274.png)


(2) Probe and body both 1 shade darker than path fill.
![image](https://user-images.githubusercontent.com/8419308/80431689-5716fc80-88af-11ea-99a5-96cab3dfbcfc.png)
![Energy Skate Park screenshot (3)](https://user-images.githubusercontent.com/8419308/80431970-297e8300-88b0-11ea-90b3-515ab74123a5.png)


(3) Probe and body both 2 shades darker than path fill.
![image](https://user-images.githubusercontent.com/8419308/80431549-fb4c7380-88ae-11ea-95a3-360bde7a7ba7.png)
![Energy Skate Park screenshot (2)](https://user-images.githubusercontent.com/8419308/80431736-7c0b6f80-88af-11ea-8846-97fe3108396a.png)

I still don't love using different colors for the probe and tool body, but I am fine with being out voted if that's what others like. My preferred option would be (3). I think the purple helps connect the tool and the path dots, even if they aren't exactly the same shade. The screen icon (see https://github.com/phetsims/energy-skate-park/issues/195#issuecomment-620279106) will likely show the probe hovering over a path dot, so that may also help users make the connection. @ariel-phet @kathy-phet thoughts?

**Comment by kathy-phet** [comment]
I like 3.

**Comment by ariel-phet** [comment]
3 works for me!

**Comment by arouinfar** [comment]
Thanks @kathy-phet @ariel-phet!

@jessegreenberg here are the todos:

- [ ] Change color of body and ProbeNode to `rgb( 103, 80, 113 )`
- [ ] Remove Path checkbox from Measure screen.
- [ ] Add Path checkbox to Intro screen, between Speed and Stick to Track.

**Comment by jessegreenberg** [comment]
OK, https://github.com/phetsims/energy-skate-park/issues/176#issuecomment-620753134 is done, reassigning to @arouinfar to review.

**Comment by arouinfar** [comment]
Looks good in master!
