### ISSUE TITLE
It would be nice to be able to put track back in toolbox

### ISSUE THREAD

**Issue by lmulhall-phet** [phetsims/energy-skate-park#181]
For https://github.com/phetsims/QA/issues/470.

It would be nice to be able to put a piece of track back in the toolbox without having to click and delete the vertices.

Would it be difficult to implement a feature that uses the y-coordinate of the cursor to determine whether the user is trying to place a track on the ground or trying to put the track back in the toolbox?

**Comment by jessegreenberg** [comment]
Ah interesting thought, something like this would be convenient. My concern is that there will be cases where the user finds this surprising. Like when trying to drag the track back to ground but mouse goes a little underground and it disappears. We don't have a "ghost" or anything that shows where the track would be below ground to indicate that it will return to toolbox.

I am curious to hear what @arouinfar thinks about this. But our deadline for this sim is approaching quickly so this may need to wait until next publication.

**Comment by arouinfar** [comment]
Thanks for the suggestion @lmulhall-phet.

> My concern is that there will be cases where the user finds this surprising. Like when trying to drag the track back to ground but mouse goes a little underground and it disappears.

Agreed.  

Would we only allow single track pieces to be dragged back into the toolbox, or would it work for connected pieces as well? Given the complicated nature of the track, I'm not sure we want to support this functionality. While it could be convenient at times, it's honestly not that inconvenient to have an extra track piece out in the play area or delete 2/3 of its vertices. 

I'm comfortable with closing rather than deferring @jessegreenberg, but I'll leave it up to you.

**Comment by jessegreenberg** [comment]
Sounds good, thanks. Closing this issue then.
