### ISSUE TITLE
Inconsistent dropdown menu layering

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/energy-skate-park#190]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/470
The drop down menus have layering such that objects (such as the skater or movable track) can be in front of part of it, and behind another when the drop down is open. 

**Visuals**
![layeringdropdown](https://user-images.githubusercontent.com/41024075/73895662-8e8c8480-483d-11ea-9e5f-7f51a2b6f1b9.png)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Energy Skate Park‬
URL: https://phet-dev.colorado.edu/html/energy-skate-park/1.0.0-dev.6/phet/energy-skate-park_en_phet.html
Version: 1.0.0-dev.6 2020-01-27 21:28:50 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by jessegreenberg** [comment]
Hmm, this is interesting, thanks. I agree this looks odd, but I think this is correct. The skater and other draggables are on top of most UI components (like the combo box button) because it would look strange if the skater got lost behind fixed buttons. But usually the ComboBox menu is on top of everything else when open. The menu is modal, it is only open when the user is actively using it. So it seems incorrect for the skater to be on top of it.

But I would love to hear @arouinfar thoughts on this.

**Comment by arouinfar** [comment]
I would agree @jessegreenberg. While it looks odd, it is indeed the correct behavior.

Here's a similar case in Masses and Springs:
![2020-02-06 16 35 34](https://user-images.githubusercontent.com/8419308/73988007-c14a8180-48fe-11ea-8c75-dff45b766941.jpg)
