### ISSUE TITLE
Images for home screen and navigation bar

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/energy-skate-park#195]
I had forgotten that we have template images for these currently, especially for Measure and Graph screens. @arouinfar can you please create new  images for this?

**Comment by jessegreenberg** [comment]
Here is what we have now
![image](https://user-images.githubusercontent.com/6396244/74454463-ef294c00-4e51-11ea-9049-616ada058db1.png)

**Comment by arouinfar** [comment]
Some rough ideas for discussion in design meeting

Intro: Skater on double well track with energy pie chart on
![image](https://user-images.githubusercontent.com/8419308/80066672-9a611c00-84f9-11ea-88f5-234caa2f09ed.png)

Measure: Skater on parabola track, path dots on, probe on dot. Data would be hidden, and the probe could be cartoonishly big.
![image](https://user-images.githubusercontent.com/8419308/80066758-cf6d6e80-84f9-11ea-842e-aeaa0b038e2a.png)

Graphs: Maybe superimpose E(x) graph over the track. Details would be simplified.
![image](https://user-images.githubusercontent.com/8419308/80067255-bfa25a00-84fa-11ea-886f-0301f4ada90e.png)

Playground: Something fun, maybe the dog in the loop. (Control points are missing because this was a quick screenshot from Intro.)
![image](https://user-images.githubusercontent.com/8419308/80066837-03e12a80-84fa-11ea-9222-9a35e5ba1057.png)

**Comment by arouinfar** [comment]
Feedback in 4/23/20 design meeting
* Try showing just the graph for the Graphs icon
* Might want to zoom in more on Playground icon

**Comment by arouinfar** [comment]
Based on our discussion during design meeting, I've cleaned up the icons. @ariel-phet can you take a look and let me know your thoughts?

| Screen | Icon |
| --- | --- |
| Intro | ![screen-icons_intro](https://user-images.githubusercontent.com/8419308/80428391-f257a400-88a6-11ea-913e-6d2858a0a56f.png) |
| Measure | ![screen-icons_measure](https://user-images.githubusercontent.com/8419308/80428396-f4216780-88a6-11ea-91bb-bd319c9c8647.png) |
| Graphs | ![screen-icons_graphs2](https://user-images.githubusercontent.com/8419308/80428965-49aa4400-88a8-11ea-8fa5-edae1940ca6e.png) |
| Playground | ![screen-icons_playground](https://user-images.githubusercontent.com/8419308/80428397-f4216780-88a6-11ea-9de3-87ebb9f26318.png) |

**Comment by ariel-phet** [comment]
@arouinfar those all look the correct direction to me. My only concern is on the navbar, so you might want to see how they look at that size, but looking at ESPB, it seems like these all should work.

**Comment by arouinfar** [comment]
Thanks for your feedback @ariel-phet! I had similar concerns about navbar readability, but these seem on par with the ESPB icons.

I cleaned up the icons a bit, and updated the color of the ProbeNode based on the decision made in #176.  @jessegreenberg here are the assets for the screen icons: 
[screen-icons.zip](https://github.com/phetsims/energy-skate-park/files/4547476/screen-icons.zip)

**Comment by jessegreenberg** [comment]
New screen icons have been added @arouinfar, can you review their look in the sim?

**Comment by arouinfar** [comment]
Looks great, thanks @jessegreenberg!
