### ISSUE TITLE
Grid lines don't drag based on deltas

### ISSUE THREAD

**Issue by samreid** [phetsims/energy-skate-park#207]
Noticed during #202, the grid lines don't drag based on deltas.  This means, for example, if you click on the top edge, then drag down, the lines jump up:

![Kapture 2020-02-28 at 9 23 13](https://user-images.githubusercontent.com/679486/75565881-05b3d380-5a0c-11ea-8776-cb86e1359310.gif)

(Note that one of the three stutters in this GIF is actually the GIF restarting though).

**Comment by jessegreenberg** [comment]
Thanks! Fixed in above commit. I also factored in the start offset so it doesn't jump if dragging starts above or below the line (like along the arrow). Back to @samreid.

**Comment by samreid** [comment]
Works great, thanks!  But I'm surprised DragListener can't do some of that arithmetic.  Can some of that work be offloaded to DragListener options?

**Comment by jessegreenberg** [comment]
I originally went with a custom drag function because we want the DragListener to control the NumberProperty `referenceHeightProperty`, which is not a Vector2Property for DragListener's `positionProperty` option.

But the above commit is an alternative that uses more of DragListener , back to @samreid to review.

**Comment by samreid** [comment]
The changes look great, thanks!  I think part of this is out to @jonathanolson for discussion in https://github.com/phetsims/energy-skate-park/issues/252, but this one can be closed.
