### ISSUE TITLE
Gravity on Jupiter is incorrect

### ISSUE THREAD

**Issue by arouinfar** [phetsims/energy-skate-park#247]
Observed in master and the prototype. When selecting Jupiter from the gravity ComboBox, the displayed value is 26.0 m/s^2. However, the value of gravity on Jupiter should be 24.8 m/s^2.

**Comment by jessegreenberg** [comment]
Interesting, thanks @arouinfar. Master is currently using the value that was used in the java sim (25.95 N/kg). Fixed in the above commit.

The range of allowable gravity is currently 1 - JUPITER_GRAVITY. So this reduced the gravity range just a little bit, is that OK?

Does the version available as the "prototype" need to be updated with this fix?

**Comment by arouinfar** [comment]
> Master is currently using the value that was used in the java sim (25.95 N/kg).

Oh wow, looks like Java was incorrect for all these years! 

> The range of allowable gravity is currently 1 - JUPITER_GRAVITY. So this reduced the gravity range just a little bit, is that OK?

I don't think the calculation is currently working in master, because the max is now `JUPITER_GRAVITY`. Does the range need to reference `JUPITER_GRAVITY`? I think a max of 26.0 was fine.


![image](https://user-images.githubusercontent.com/8419308/78193141-0985ac00-7437-11ea-9afd-251041355c59.png)

**Comment by arouinfar** [comment]
> Does the version available as the "prototype" need to be updated with this fix?

Once this issue is worked out, it might be nice to republish if master is in a good place.

**Comment by jessegreenberg** [comment]
> I think a max of 26.0 was fine.

OK sounds good. Lets publish a new version after #240 is done, unless it is important to fix this right away, @arouinfar let me know.
