### ISSUE TITLE
User suggestion: Potential label, acceleration units

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/energy-skate-park#293]
> I first want to express my thanks for the continued work on the PhET simulations - the time and effort put into each one is clear! I am especially grateful for the newest updates to the Energy Skate Park, which has made it infinitely more usable with my classroom's pedagogy (modeling instruction).
> 
> I have a few points of feedback for improvements, from the ground (classroom) level, that I think would make it an even better simulation.
> 
> **Change "Potential" to "Gravitational"** - there is a push among many high school teachers to avoid the use of the term "potential energy" (at least in isolation). Even putting aside that there are many potential energies (elastic potential, electric potential, etc.), the word "potential" actually creates misconceptions in middle and high school students, who don't understand that "potential" energy is as real as kinetic, thermal, or any other mode of energy storage.
> 
> My request would be to change the labels in the bar graph and pie chart to say Kinetic, Gravitational, and Thermal. "Gravitational Potential" would also be okay, if it's important for others who use the simulation to keep the word potential in there.
> 
> **Change "m/s^2" to "N/kg" and add Pluto** - in the "Measure" section, the gravitational field strength (just labeled "Gravity") is customizable - which is great! But, like the word "potential," I would request that the units used for this are Newtons per kilogram (N/kg), rather than meters/second^2. The units m/s/s have far less intuitive understanding than N/kg. Anecdotally, I have had many students say that the gravitational field strength of Earth on a ball at rest on a table is 0, "because the ball is not accelerating." This comes directly from the confusion of acceleration units describing the gravitational field. Tying the gfs directly to the mass avoids this confusion, and leaves the connection for a later lab on Newton's 2nd Law.
> 
> This is perhaps even more obscure than my "potential" argument, so I understand if there's some pushback. If you are interested in hearing a more coherent argument (I'm trying to keep this email as short as I can), I would be happy to follow up and plead the case!
> 
> One final request - although he is no longer a planet, I would love to be able to have my students set the gfs to Pluto's magnitude, which is 0.49 N/kg. Currently, the gfs only goes to 1 N/kg!

**Comment by arouinfar** [comment]
I appreciate the user's feedback, and they've clearly given this a lot of thought.  While I can appreciate some of the points they make, I am not inclined to make any of these changes. 

When I think about the broader audience of this sim (global usage in high school and university), it is important to stick to conventional names and units. I also think a lot of the user's issues are easily addressed in how teachers facilitate the use of the sim.

> Change "Potential" to "Gravitational"

The word "potential" has specific meaning in physics, and I would never consider removing it from the label. Gravitational, elastic, and electrostatic potential energies are all derived from their respective forces.  We could call it "gravitational potential", but I honestly think it's too verbose and would pose i18n issues.

> the word "potential" actually creates misconceptions in middle and high school students, who don't understand that "potential" energy is as real as kinetic, thermal, or any other mode of energy storage.

I did look through Phys Rev PER and The Physics Teacher to see if I could find any articles dealing directly with this issue, but I didn't find anything. However, my search was more of a sanity check than a full-on literature review.

> Change "m/s^2" to "N/kg" and add Pluto

The SI unit of acceleration is `m/s^2`. Acceleration is the rate of change of velocity (m/s)/s. In the context of gravitational force/potential energy, I can appreciate that thinking in terms of `N/kg` could potentially help students with sense-making. However, I think we would be remiss in using non-standard (though equivalent) units in how we represent the acceleration due to gravity. We must also bear in mind that our simulations are used worldwide and across a variety of grade levels. What might work better in this particular user's classroom does not necessarily scale with our usage.

Adding Pluto (either indirectly by expanding the slider range, or directly by adding it the Combobox) would certainly add whimsy, but this sim already has a lot of whimsy. The current range is more than enough to support the learning goals. There are some practical reasons for keeping the range as-is. According to [NASA](https://nssdc.gsfc.nasa.gov/planetary/factsheet/plutofact.html) the acceleration due to gravity on Pluto is 0.62 m/s^2. We chose to display only one decimal place so, this would be rounded to 0.6 m/s^2. If we want the range to have cleaner-looking numbers, the new slider minimum would be 0.5 m/s^2. We currently use `constrainValue` to snap the slider thumb in increments of 1.0 m/s^2, but with this new range that would need to be changed to 0.5 m/s^2.  This essentially doubles the number of steps accessible to users interacting with the slider thumb only, making values more difficult to reproduce.

@ariel-phet  can you read through this and let me know your thoughts?

**Comment by ariel-phet** [comment]
@arouinfar I generally agree with everything you say:

1. Although calling Potential Energy, Gravitational Potential Energy would be more accurate, since that is the only potential energy available in the sim, I agree with you, it just does not make sense to change.

2. We are definitely not going to use nonstandard units as the default. That being said, `N/kg` are certainly an equivalent unit so really only the label would change if we allowed this option. I **would** actually be in favor of adding a query parameter/option to support this request -- mainly because it seems easy to support and probably just a few lines of code to add a query parameter.

3. I agree that adding Pluto would be problematic. The learning goals already seem well met by the options we have. If I were going to do anything it would be to add a "planet X" and have a mystery value. If we did that, we could have a planet (or two) outside of the exploration range of the slider. As in other sims, if the mystery planet were chosen the slider would be gone perhaps and the gravity would just read a "?" .

**Comment by arouinfar** [comment]
@ariel-phet I generally like the idea of adding `N/kg` support behind a query parameter. I think it would make the most sense to have a flag-type query parameter like `altGravityUnits` which sets things to `N/kg`. A string-type could get pretty awkward when trying to spell out units in camel case, such as `gravityUnits=nPerKg` or `gravityUnits=mPerSPerS`.

A Mystery Planet would be a bit tricky in this sim, so I don't know that I'd include one. We usually replace the slider with the string like "What is the value of gravity?". This sort of challenge works on the Measure screen, but isn't really feasible on the other screens. If the mystery value is out of the slider range, we'd likely need to adjust the graph zoom levels too.

**Comment by ariel-phet** [comment]
@arouinfar sounds good, lets just go with a query parameter in that case. `altGravityUnits` sounds good to me. Might be worth getting @kathy-phet opinion at a design meeting in the near future since this sim will get some iO attention soon.

**Comment by jessegreenberg** [comment]
During meeting @ariel-phet suggested `altAccelerationUnits` as the name. It will display `N/kg` in the number display for the gravity number control. We will include this in the initial publication of the sim.

**Comment by jessegreenberg** [comment]
This was added in the above commit. @arouinfar can you please verify that this is working correctly in master?

**Comment by arouinfar** [comment]
It looks good in master, thanks @jessegreenberg.

I want to make sure we let the user know about the query parameter when the sim is published, so leaving this self-assigned and marking as fixed.

**Comment by jessegreenberg** [comment]
Addition moved to the 1.1 release branch.

**Comment by KatieWoe** [comment]
This looks good in rc.2

**Comment by jessegreenberg** [comment]
Thanks for reviewing @KatieWoe - sorry I should have labelled this differently I think @arouinfar wanted to keep this open as a reminder to notify user when this is ready for public use.

**Comment by arouinfar** [comment]
@oliver-phet can you reach out to the user and let them know that the simulation has been published with the `altAccelerationUnits` query parameter, and they can use this link to view gravity with units of N/kg:
https://phet.colorado.edu/sims/html/energy-skate-park/latest/energy-skate-park_en.html?altAccelerationUnits

**Comment by oliver-phet** [comment]
Email to user sent, closing!

**Comment by oliver-phet** [comment]
Reply from user:
> Please pass along my thanks for making the new query parameter - that will solve most of my main concerns. I haven't given up on "gravitational potential" but I can hand-wave it away - perhaps I'll get another chance to convince the team in the future. ;-)
> 
> Happy holidays to the entire PhET team - you are all appreciated more than you know, out here in the teaching wilderness! Please make sure you all take care of yourselves and take some time away from work - I hope 2021 is more restful and rewarding all around.
