### ISSUE TITLE
User request: add measurement points to allow comparison

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/energy-skate-park#297]
> Measurements can only be made at the purple dots the skater leaves behind.  But the purple dots do not appear at the same places on consecutive runs, making accurate comparisons between runs impossible.  Perhaps once the placement of dots is established on the first run, they can just stay in the same place instead of being repopulated?

I suggested to the user that perhaps we could add measurement points at grid intersections (when Grid is enabled). This would allow them to isolate friction (or other variables) and see how each energy parameter changes.

@arouinfar I believe the measurement points are created every .1 second? Is that correct?

**Comment by arouinfar** [comment]
>@arouinfar I believe the measurement points are created every .1 second? Is that correct?

That's correct, @oliver-phet. Drawing the dots at equal time steps allows users to see the velocity along the track (e.g. faster at the bottom). If the time it takes for the skater to reach the end of the track is perfectly divisible by 0.1 s, the dots would exactly draw on top of themselves. However, this is very unlikely to happen, and you're more likely to end up in a situation where the dots layer on top of each other and no longer make sense, as was the case in Java.
![image](https://user-images.githubusercontent.com/8419308/96058658-12752280-0e49-11eb-9fe9-94059bf00e3b.png)

My initial reaction was to suggest that the user use the "Restart Skater" button when repeating test runs. This would work if the dots start drawing exactly 0.1 s after the skater is released, but that isn't the case (see #298).

> I suggested to the user that perhaps we could add measurement points at grid intersections (when Grid is enabled

This is an interesting suggestion @oliver-phet. I tried drawing special dots every 1m to see what it would look like. I think it gets pretty busy and makes it harder to interpret the spacing of the purple dots. The movable reference height (which shifts the grid) would also complicate things.
![image](https://user-images.githubusercontent.com/8419308/96060409-a6e18400-0e4d-11eb-8521-fb9cd88312f6.png)

Let's see what happens in #298 before replying to the user.

**Comment by arouinfar** [comment]
@oliver-phet we fixed the start time of the first dot in #298, and the Restart Skater button now restores the same state. Can you reply to the user with the following message?

The purple dots are drawn every 0.1 seconds, so there will always be some slight variation  in the dot position when the skater moves back and forth on a frictionless track. However, pressing the "Restart Skater" button will repeat the exact same path. There is a bug in the prototype that leads to different start times of the first dot, but that has now been corrected and will behave properly in the published simulation. We cannot leave dots in place after an established first run because the implementation needs to support situations with friction.

**Comment by oliver-phet** [comment]
Reply to user sent.
