### ISSUE TITLE
Moon gravity reads as custom if achieved with number spinner

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/energy-skate-park#301]
**Test device**
MacBook Air
**Operating System**
MacOS 10.15.7
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/544. I think it may be connected to https://github.com/phetsims/energy-skate-park/issues/251.
When you use the number spinner to adjust the gravity of the sim, and you land on 9.8 or 24.8 the combo box text changes to say Earth or Jupiter, respectively. But, when it goes to 1.6, it still says Custom, rather than Moon. It only says Moon if you use the combo box to get to it.
**Steps to reproduce**
1. Go to the second, third, or forth screen.
2. Use the slider and number spinner to set gravity to 9.8, 24.8, and 1.6

**Visuals**
![mooniscustomgravity](https://user-images.githubusercontent.com/41024075/96520064-7b82de80-122b-11eb-9c5e-130a05f44a4f.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Energy Skate Park‬
URL: https://phet-dev.colorado.edu/html/energy-skate-park/1.1.0-rc.1/phet/energy-skate-park_all_phet.html
Version: 1.1.0-rc.1 2020-09-02 16:48:45 UTC
Features missing: applicationcache, applicationcache, touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.80 Safari/537.36
Language: en-US
Window: 1294x685
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by arouinfar** [comment]
Thanks @KatieWoe. Generally the ComboBox would always display "Custom" when the value is adjusted with the NumberControl, but we chose not to do that in this sim so that the playback would behave correctly on the Graphs screen, see #280.

This looks like the behavior described in https://github.com/phetsims/energy-skate-park/issues/280#issuecomment-661518050 onwards was reverted, specificially:
> During playback, the sim adjusts the model property for gravity and doesn't know if the values it restores were originally set by the NumberControl or ComboBox. Previously, the ComboBox would only read "Custom" during playback. It now shows "Earth", etc. during playback, but **the side effect is that the ComboBox will display the benchmark if the corresponding value was set using the NumberControl.**

**Comment by jessegreenberg** [comment]
This is happening because the constant for moon's gravity is more precise than the precision of the number control. The moon's gravity is 1.62 m/s^2, but the arrow buttons set it to 1.6.  So currently, when you select "Moon" the gravity is actually a little larger than what is shown.
![image](https://user-images.githubusercontent.com/6396244/97607472-65251180-19e7-11eb-96a7-f440fb44e22b.png)


The fix will be to either increase precision of the NumberControl or bring moon's gravity down to 1.6 in the sim. @arouinfar what do you think is best?

So currently, when you

**Comment by arouinfar** [comment]
@jessegreenberg the constants should have the same precision as the readout, so let's change the moon's gravity to 1.6 m/s^2 in the model.

**Comment by jessegreenberg** [comment]
OK, thank you - done in the above commit.

**Comment by jessegreenberg** [comment]
Cherry-picked into release branch.
