### ISSUE TITLE
Side of ramp moves without dragging it in Playground scene

### ISSUE THREAD

**Issue by brooklynlash** [phetsims/energy-skate-park#312]
**Test device**
Lenovo ThinkPad

**Operating System**
Windows 10

**Browser**
Chrome

**Problem description**
This is for https://github.com/phetsims/QA/issues/579
Not sure how long this has been a problem or if it even is a problem, but when I drag one side of the ramp on ESP Playground scene, the other side moves. 
This is also seen in the published ESP Basics. 
Note: The resolution in the sky is an issue with the gif application I am using.

**Steps to reproduce**
1. Open Playground. 
2. Grab a ramp
3. Drag one of the sides quickly away from the other side, to make it longer (i.e. if grabbing right side, move it far to the right quickly)
4. Observe the other side

**Visuals**
![espplayground](https://user-images.githubusercontent.com/72031637/99837856-744e3980-2b25-11eb-8cd3-adb3e502d9b3.gif)

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Energy Skate Park‬
URL: https://phet-dev.colorado.edu/html/energy-skate-park/1.1.0-rc.4/phet/energy-skate-park_all_phet.html
Version: 1.1.0-rc.4 2020-11-19 04:43:37 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4095
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

**Comment by jessegreenberg** [comment]
Thanks for making an issue @brooklynlash. It seemed a little strange to me that this could happen from a brand new track where control points were in a line. However, since both @brooklynlash and I were able to observe this in the published ESP:B version, this is not new and is from original code that generates the track shape.

@arouinfar can you please review this issue and comment on whether anything should be done now or at a later release, or if this can just be closed with wontfix?

**Comment by arouinfar** [comment]
Nice find @brooklynlash! 

It does look a bit weird, especially with new, flat track pieces. However, the effect is pretty minor and it doesn't occur unless the control point is moved fast enough. Given that this is fairly minor, has been around since Basics, and the fix could disturb other things in the already-complicated control point code, I think we can go ahead and close as wontfix.
