### ISSUE TITLE
Use MagnifyingGlassZoomButtonGroup

### ISSUE THREAD

**Issue by samreid** [phetsims/energy-skate-park#315]
Scenery-phet now has support for ZoomButtonGroup, it seems like Energy Skate Park could delete many lines of code if it used that new common code.

Noticed during https://github.com/phetsims/circuit-construction-kit-common/issues/620

**Comment by jessegreenberg** [comment]
I read through https://github.com/phetsims/circuit-construction-kit-common/issues/620 and it seems likely that this would be a sim to use ZoomButtonGroup because it looks more modern and there isn't overload in concept with "+" and "-" symbols in this sim.  Using ZoomButtonGroup will be tracked in #313.

@arouinfar can you please review and close if you agree?

**Comment by arouinfar** [comment]
I think we will probably end up using ZoomButtonGroup, but that's something we'll decide on in #313 during the PhET-iO design review.
