### ISSUE TITLE
CT Error - phetioElement not found: energySkatePark.measureScreen.measureScreenView.trackNodeGroup.archetype.controlPointNode0

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/energy-skate-park#318]

**Comment by jessegreenberg** [comment]
I am not sure, but I think this may be related to #123 - Maybe the ControlPointNodes of TrackNode need to use PhET-iO group as well? Maybe this isn't compatible with changes in #123. 

```js
tandem.createTandem( 'controlPointNode' + i )
```

@samreid what do you recommend, should I try PhetioGroup or do you think the issue is somewhere  else?

**Comment by samreid** [comment]
This seems related to work I've done in the last few days, I'll take a look.

**Comment by samreid** [comment]
I disabled phet-io validation for energy-skate-park-basics until we enable it for both energy-skate-park as well.

**Comment by samreid** [comment]
The problem seems to be that the archetype only had 2 control points, but the actual track had 3, so it failed to see that last control point.  For now I've solved this by increasing the number of control points in the archetype.  I'm not sure if the long term solution is to use a PhetioGroup for the archetype.  It's working on my local side, and we may need to defer the long term solution until we are focusing more on next phet-io publication for these sims.  Closing.
