### ISSUE TITLE
User request: draggable charts

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/energy-skate-park#321]
> In the skateboard park sims, could the energy bar chart either be made draggable, so that it can be moved out of the way, or at least lined up with the grid, so the bottom of the chart lines up exactly with the 2 m line? Then students can use it as a reference when sketching bar heights.

**Comment by arouinfar** [comment]
We are not going to make the charts draggable. It's not something that AccordionBox would (or should) support, and it'd create other UX problems. Shifting the base of the bar graph is also not an option. The whitespace is needed to display negative energies as well as leave room for i18n of the graph labels. 

This user has a very particular goal of students sketching the bar graph. Some things I would suggest:

* Instead of sketching the bar graph, take screenshots 
* Collect data using the probe on the Measure screen and make your own bar chart
* Use the measuring tape to measure the height of the bars (would need a scale to convert it to graph paper, perhaps 0.5 m = 1 grid square).
* Use the movable potential energy reference line to shift the position of the grid to align with the bar graph. To avoid negative potential energy, use the Playground screen and build a custom track above the reference line.

**Comment by oliver-phet** [comment]
Thanks! I've replied back to the user.
