### ISSUE TITLE
Consider scaling skater artwork differently

### ISSUE THREAD

**Issue by arouinfar** [phetsims/energy-skate-park#361]
Currently, all human skaters have the same dimensions. 
<img width="995" alt="image" src="https://user-images.githubusercontent.com/8419308/208532338-d0f31b6c-f8a3-4a3d-8852-7965cefac077.png">

This means that skaters with the same weight will have the same height. However, it also means that the younger-appearing skaters look a bit large in comparison to the older-appearing skaters.

| Skater 1 | Skater 6 |
| --- | --- |
|  <img width="645" alt="image" src="https://user-images.githubusercontent.com/8419308/208532434-42e09506-bfe9-40b5-846d-56dfb479de4e.png"> | <img width="638" alt="image" src="https://user-images.githubusercontent.com/8419308/208532472-30a98a17-a62d-424c-80e9-737c68ac0278.png"> | 

When this sim is revisited for PhET-iO, let's consider if there are alternatives to how we scale the skater artwork.

**Comment by marlitas** [comment]
We are touching skater artwork on energy skate park now and this issue seems like a good candidate to include in the new publication. I'll remove the deferred label.

However, I am a bit confused by this comment:
"This means that skaters with the same weight will have the same height."

I didn't notice a mass change between the different skaters in the sim, so I wasn't sure if weight is having an effect in some other way? @arouinfar

**Comment by Luisav1** [comment]
This was addressed over in https://github.com/phetsims/energy-skate-park/issues/374. The height of the characters was adjusted for their relative size.
