### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/energy-skate-park#362]
For https://github.com/phetsims/qa/issues/870. Seen on Win 11 Chrome
These are the results from the memory test. It seems to indicate a memory leak somewhere.
![skatemem](https://user-images.githubusercontent.com/41024075/209404039-d9a2428a-9302-4d0a-849d-9af5963552a8.png)

**Comment by jessegreenberg** [comment]
Thanks @KatieWoe. I wonder if this is caused by recent string -> StringProperty conversions in #350.

**Comment by samreid** [comment]
@AgustinVallejo and @jbphet will coordinate on this on Jan 4, thanks!

**Comment by samreid** [comment]
@jonathanolson also corrected a memory leak in font awesome nodes in this commit: https://github.com/phetsims/sherpa/commit/68ffa3d6dd27d98eb369795faec54e958cb3c25b

I tested fuzzing for 20 minutes and it seems stable. I think this issue is ready to close.
<img width="136" alt="image" src="https://user-images.githubusercontent.com/679486/210655383-01e139b2-39a5-4d31-aea2-1983c1b2ae33.png">

Though I am not sure the full timeline or steps to recreate a table like https://github.com/phetsims/energy-skate-park/issues/362#issue-1509765027.  @AgustinVallejo do you think this issue can be closed?  Do you want a double check by @KatieWoe ?

**Comment by samreid** [comment]
I got another reading at 30 minutes, so I'm feeling more confident about this:

<img width="136" alt="image" src="https://user-images.githubusercontent.com/679486/210656220-c987217e-bb8d-4676-ac2c-85d5f6a0a8c4.png">

**Comment by KatieWoe** [comment]
Memory test looks good in rc.2
![newmem](https://user-images.githubusercontent.com/41024075/212200849-a92247b2-6117-46a1-b70d-43e36449e6ae.png)
