### ISSUE TITLE
Issues with renderer: webgl on bar graph and labels

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/energy-skate-park#39]
Two sub-issues from #25. I changed the bar graph labels and bars so that they can be stroked. After adding a stroke to the rectangle, the graph bars are jiggling up and down when the bar size changes.

Here is the rectangle, `renderer: 'webgl'` is set on a parent node:
```js
var solidBar = new Rectangle( barX, 0, barWidth, 100, { fill: color, pickable: false, stroke: 'black', lineWidth: 0.5 } );
```

The other issue I am seeing is that an image rendered with WebGL, created from rasterize() has grey artifacts around the edges.
![capture](https://user-images.githubusercontent.com/6396244/48650821-d66b8580-e9c5-11e8-9330-189c683586d1.PNG)

```js
      // wrap with a rounded rectangle with some opacity so that it shows up on top of the bar
      var outlineRectangle = new Rectangle( label.bounds.dilated( 2 ), { fill: EnergySkateParkColorScheme.transparentPanelFill } );
      outlineRectangle.addChild( label );
      var imageNode = outlineRectangle.rasterized( { resolution: 8, wrap: false } );
```

**Comment by jessegreenberg** [comment]
The jiggling is also very apparent with the label text now that they are part of the front layer.

I see that fitted block bounds update with the bars, don't know if that is related? Either way I think I remember that disabling this could improve performance?
![fitted](https://user-images.githubusercontent.com/6396244/48651088-3f073200-e9c7-11e8-84f8-45f81a708cb1.PNG)

**Comment by jessegreenberg** [comment]
Yep, preventFit: true on the bar graph foreground fixes the jiggling.

**Comment by jessegreenberg** [comment]
Here is the code that causes the grey stroke:
```js
  var bar = new Node( { renderer: barRenderer } );
  var label = barGraphBackground.labelMap[ index ];
  labelRectangle.addChild( label );
  var imageNode = labelRectangle.rasterized( { resolution: 8, wrap: false } );
```

where barRenderer is 'webgl'. In barGraphForeground.createBar. @jonathanolson do you know what may be causing this?

**Comment by jonathanolson** [comment]
My suspicion is that the rasterization adds on a few pixels on the side of the labelRectangle that get recorded (which are probably being recorded as black with zero alpha - transparent), but that something is going on that is incorrectly doing some blending between pixel values, resulting in that transparent black leaking.

It looks like this is happening in master, so I'll investigate.

**Comment by jonathanolson** [comment]
This got pretty complicated, but Scenery was basically using a style of alpha/transparency that apparently doesn't mix well with texture lookups.

It turns out the texture2d lookups in shaders is basically assuming that the texture's color values are premultiplied (RGB values are assumed to essentially be R*A, G*A, B*A), so that when it interpolates between two values, if they differed in alpha, it was giving incorrect results. Scenery was using a somewhat workaround blending function configuration in order to use non-premultiplied color in most cases.

I set up a testing suite with all the possible types of blending, and retrofitted things to a more "standard" blending function, along with consistently using premultiplied colors. For textures, Scenery assumes they ARE premultiplied, and assumes color inputs are NOT premultiplied.

Before (top is SVG/Canvas, bottom is WebGL):
<img width="514" alt="screen shot 2018-11-27 at 12 41 02 am" src="https://user-images.githubusercontent.com/480878/49066062-3390e380-f1dd-11e8-8210-f589be70d82f.png">

After:
<img width="513" alt="screen shot 2018-11-27 at 12 40 15 am" src="https://user-images.githubusercontent.com/480878/49066074-3ee40f00-f1dd-11e8-8a4b-f006b5f20f21.png">

https://stackoverflow.com/questions/39341564/webgl-how-to-correctly-blend-alpha-channel-png was also very helpful. Due to the texture2d lookup issue, we can't actually use some of the options suggested.

@ariel-phet, since this is basically a rework of how transparency/alpha is handled for WebGL (along with patches for sims with custom WebGL with transparency, e.g. ESPB/ESP/neuron/bending-light), I'm curious whether you feel testing should be done. Some platforms may handle things slightly differently, although that would probably be caught in RCs. Thoughts?

**Comment by jonathanolson** [comment]
Testing issue created in https://github.com/phetsims/QA/issues/226. @jessegreenberg anything else that should be done?

**Comment by jessegreenberg** [comment]
Thanks so much @jonathanolson, it is looking great in master, all issues listed in this issue have been fixed. Closing.
