### ISSUE TITLE
Automated Testing Sim Error

### ISSUE THREAD

**Issue by phet-steele** [phetsims/energy-skate-park#45]
This seems very very very rare. Mentioning @samreid but keeping unassigned unless he feels like tackling it:
```
Error: Assertion failed: undefined
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1491448434672/assert/js/assert.js:21:13)
    at SkaterState.switchToGround (https://bayes.colorado.edu/continuous-testing/snapshot-1491448434672/energy-skate-park-basics/js/energy-skate-park-basics/model/SkaterState.js?bust=1491454026944:182:19)
    at EnergySkateParkBasicsModel.switchToGround (https://bayes.colorado.edu/continuous-testing/snapshot-1491448434672/energy-skate-park-basics/js/energy-skate-park-basics/model/EnergySkateParkBasicsModel.js?bust=1491454026944:487:26)
    at EnergySkateParkBasicsModel.stepFreeFall (https://bayes.colorado.edu/continuous-testing/snapshot-1491448434672/energy-skate-park-basics/js/energy-skate-park-basics/model/EnergySkateParkBasicsModel.js?bust=1491454026944:508:21)
    at EnergySkateParkBasicsModel.stepTrack (https://bayes.colorado.edu/continuous-testing/snapshot-1491448434672/energy-skate-park-basics/js/energy-skate-park-basics/model/EnergySkateParkBasicsModel.js?bust=1491454026944:897:21)
    at EnergySkateParkBasicsModel.stepModel (https://bayes.colorado.edu/continuous-testing/snapshot-1491448434672/energy-skate-park-basics/js/energy-skate-park-basics/model/EnergySkateParkBasicsModel.js?bust=1491454026944:1149:39)
    at EnergySkateParkBasicsModel.step (https://bayes.colorado.edu/continuous-testing/snapshot-1491448434672/energy-skate-park-basics/js/energy-skate-park-basics/model/EnergySkateParkBasicsModel.js?bust=1491454026944:414:31)
    at EnergySkateParkBasicsSim.stepSimulation (https://bayes.colorado.edu/continuous-testing/snapshot-1491448434672/joist/js/Sim.js?bust=1491454026944:764:24)
    at EnergySkateParkBasicsSim.runAnimationLoop (https://bayes.colorado.edu/continuous-testing/snapshot-1491448434672/joist/js/Sim.js?bust=1491454026944:699:14)
Approximately 4/5/2017, 9:13:54 PM
```

**Comment by samreid** [comment]
Transferred since this code lives in energy-skate-park now.

**Comment by samreid** [comment]
I left two sims fuzzing for half an hour and this error did not occur.  Here is the code that is causing it:

```js
    switchToGround: function( skaterState, initialEnergy, proposedPosition, proposedVelocity, dt ) {
      var segment = new Vector2( 1, 0 );

      var newSpeed = segment.dot( proposedVelocity );

      // Make sure energy perfectly conserved when falling to the ground.
      var newKineticEnergy = 0.5 * newSpeed * newSpeed * skaterState.mass;
      var newPotentialEnergy = ( -1 ) * skaterState.mass * skaterState.gravity * ( 0 - skaterState.referenceHeight );
      var newThermalEnergy = initialEnergy - newKineticEnergy - newPotentialEnergy;

      if ( !isFinite( newThermalEnergy ) ) { throw new Error( 'not finite' ); }
      return skaterState.switchToGround( newThermalEnergy, newSpeed, 0, proposedPosition.x, proposedPosition.y );
    },
```

For Energy Skate Park (not basics), the potential energy can go negative, depending on the height of the reference line--but this calculation can make the thermal energy go negative, which is not allowed.

We could change the thermal energy calculation to always remain >=0 like so:

```js
var newThermalEnergy = Math.max( initialEnergy - newKineticEnergy - newPotentialEnergy, 0 );
```

But then total energy wouldn't be conserved.  But since this problem is exceedingly rare and we don't know what causes it, this solution may be reasonable to prevent it from showing up on CT?

Another possibility would be to add more information to the assertion text so when they appear on CT we have more clues as to what is going wrong here.  I'll start with that.

**Comment by samreid** [comment]
I added more information to the assertion message so we can try to understand what is happening.  On hold until this comes up again in CT.

**Comment by jessegreenberg** [comment]
This came up in #60, here is the report from that issue:
```
energy-skate-park : fuzz : require.js : run
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Thermal energy should be non-negative: skaterState: [object Object], initialEnergy: -0.000052499999946185295, proposedPosition: Vector2(-7.571110223793646, 0), proposedVelocity: Vector2(-2.5797371235970383e-12, -0.016666666666692725), dt: 0.016666666666666666, newSpeed: -2.5797371235970383e-12, newKineticEnergy: 1.7469489520519892e-22, newPotentialEnergy: 0, newThermalEnergy: -0.000052499999946185295, referenceHeight: 0, tracked in https://github.com/phetsims/energy-skate-park/issues/45
Error: Assertion failed: Thermal energy should be non-negative: skaterState: [object Object], initialEnergy: -0.000052499999946185295, proposedPosition: Vector2(-7.571110223793646, 0), proposedVelocity: Vector2(-2.5797371235970383e-12, -0.016666666666692725), dt: 0.016666666666666666, newSpeed: -2.5797371235970383e-12, newKineticEnergy: 1.7469489520519892e-22, newPotentialEnergy: 0, newThermalEnergy: -0.000052499999946185295, referenceHeight: 0, tracked in https://github.com/phetsims/energy-skate-park/issues/45
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1550029257249/assert/js/assert.js:22:13)
    at LabModel.switchToGround (https://bayes.colorado.edu/continuous-testing/snapshot-1550029257249/energy-skate-park/js/energy-skate-park/common/model/EnergySkateParkModel.js?bust=1550056520462:495:17)
    at LabModel.stepFreeFall (https://bayes.colorado.edu/continuous-testing/snapshot-1550029257249/energy-skate-park/js/energy-skate-park/common/model/EnergySkateParkModel.js?bust=1550056520462:530:21)
    at LabModel.stepTrack (https://bayes.colorado.edu/continuous-testing/snapshot-1550029257249/energy-skate-park/js/energy-skate-park/common/model/EnergySkateParkModel.js?bust=1550056520462:992:21)
    at LabModel.stepModel (https://bayes.colorado.edu/continuous-testing/snapshot-1550029257249/energy-skate-park/js/energy-skate-park/common/model/EnergySkateParkModel.js?bust=1550056520462:1302:39)
    at LabModel.step (https://bayes.colorado.edu/continuous-testing/snapshot-1550029257249/energy-skate-park/js/energy-skate-park/common/model/EnergySkateParkModel.js?bust=1550056520462:400:31)
    at first (https://bayes.colorado.edu/continuous-testing/snapshot-1550029257249/joist/js/Sim.js?bust=1550056520462:217:24)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1550029257249/axon/js/Emitter.js?bust=1550056520462:251:55)
    at EnergySkateParkSim.stepSimulation (https://bayes.colorado.edu/continuous-testing/snapshot-1550029257249/joist/js/Sim.js?bust=1550056520462:920:34)
    at EnergySkatePar
```

**Comment by jessegreenberg** [comment]
I notice that the initial energy is equal to newThermalEnergy. It is less than zero with a reference height of 0. Maybe the skater is just slightly below y=0 when this is happening.

**Comment by jessegreenberg** [comment]
I tried to get the skater fall off the track below ground. I thought this might be possible by dragging a control point while the skater was moving on the track like this:
![image](https://user-images.githubusercontent.com/6396244/52822482-cc6a2900-307f-11e9-93a5-39e79f445341.png)

I tried to delete the end point in the above image too, I thought that might initiate 'switchToGround` immediately but the sim handled that gracefully and we didn't hit the assertion.

**Comment by jessegreenberg** [comment]
@samreid and I met to investigate this today. We found that this may be caused by a correction to the updated energy to make sure that total energy is conserved during calculations. We found one case of this (different from the case listed in this issue) in `stepGround`. In this case, `stepGround` tries to keep the same energy by removing the energy difference from the thermal energy. But if the difference is larger than the thermal energy we can get negative thermal energy. 

We were able to consistently produce this case when the skater starts below ground by doing the following:
1) Disabling `Track.bumpAboveGround` to create reproducible tests.
2) Create a track that goes below ground.
3) Run skater on the track and pause when it goes below ground.
4) Clear thermal energy.
5) Delete the track.
6) Step forward in time.

This results in a temporary negative thermal energy.

The fix we are going to try is to remove energy from kinetic energy instead in this case, as long as this correction doesn't make kinetic energy negative.

**Comment by jessegreenberg** [comment]
Potential fix in the above commit, but I don't think it is quite correct yet. Result of above commit wouldn't remove from kinetic energy but just set velocity to its absolute value. We need to calculate the  new velocity that would come from reducing the kinetic energy.

**Comment by jessegreenberg** [comment]
I think the above commit is what we want. We think a similar thing is happening in `switchToGround`.

**Comment by jessegreenberg** [comment]
I am not sure how this is happening from switchToGround during CT yet, but one way to force this error to happen is to 
1) comment out `bumpAboveGround`
2) Comment out code in ControlPointNode drag handler that keeps control points above ground
3) Make a track that would send the skater off below ground:
![image](https://user-images.githubusercontent.com/6396244/63188660-eb964300-c02f-11e9-86c7-1493f9a17e78.png)
4) Set friction to "None"
5) Put skater on track.

**Comment by jessegreenberg** [comment]
This is happening because we are adding potential energy to the system when we call `switchToGround`. The skater is moved up relative to the reference height. So we try to correct by removing energy from somewhere else. This comment makes me think that switchToGround was designed only to conserve energy when the skater falls to the ground (which is very reasonable).
> // Make sure energy perfectly conserved when falling to the ground. @samreid what do you think?

After thinking about this more, I question whether we actually want to conserve energy in this case. We are "popping" the skater above ground, which is non-physical anyway.

**Comment by samreid** [comment]
Thanks for the investigation @jessegreenberg.  I'm not sure what's best for this case.  It seems reasonable to increase energy when popping the skater from underground to above ground.  But since we don't know how this is triggered on CT, it is difficult to say whether students would be able to set up a case where energy is not conserved.   Brainstorming other alternatives:

a) Don't let the skater go below ground in the first place.  If they are on a track which is about to take the skater below ground, they could transfer to the ground instead of going underground.  This would conserve energy but may create an unexpected trajectory for the skater.  May be annoying if the user set up a track which looks like it is above ground or just touches the ground but actually numerically has some sample points below ground.
b) When the skater tries to `switchToGround` from below ground, just freeze the skater at its below-ground location and convert the kinetic energy to thermal.  This would conserve energy but may seem odd or buggy that the skater pauses underground.

I'm not confident at all about whether to pursue one of these ideas or the proposal to just add total energy to the system.  I'd like to discuss it further with @jessegreenberg and potentially also @ariel-phet.

**Comment by jessegreenberg** [comment]
I like both of these suggestions @samreid. (a) seems best to me. For any track that is not being actively constructed, Track.bumpAboveGround should make sure that all samples are above y = 0. So the issue you point out should only be a problem if track or control point are being dragged.

**Comment by samreid** [comment]
Let's touch base with @ariel-phet on this idea before implementing.  @ariel-phet can you please think through the last few comments and let us know your recommendation?

**Comment by jessegreenberg** [comment]
(a) seems quick to do so I tried it for the sake of discussion in https://github.com/phetsims/energy-skate-park/commit/da722dda4097d77aec2a8d863b0e3467edbc9d78 though if we keep this it would be good to verify that this is correct.  Here is a gif.

![cf1ac2d94738727279a0c3df84f3e4fc](https://user-images.githubusercontent.com/6396244/67134279-7a197300-f1df-11e9-82db-e6ac388e283c.gif)

There is a flicker of negative potential energy, work on removing that.

@ariel-phet and @arouinfar can you please review the above comments and let us know if you think this is reasonable? Please let me know if it would be better to discuss in meeting for more context.

**Comment by jessegreenberg** [comment]
I met with @arouinfar for this today - @arouinfar agreed that option a is reasonable and thinks we should go ahead with that as a solution. I will finish up that fix and make sure the issue identified in https://github.com/phetsims/energy-skate-park/issues/45#issuecomment-544010202 is resolved. We also found an issue where the skater would switch to ground on some premade tracks because they weren't bumped above ground initially, I will fix that too.

**Comment by jessegreenberg** [comment]
> We also found an issue where the skater would switch to ground on some premade tracks because they weren't bumped above ground initially, I will fix that too.

That portion fixed in the above commit.

**Comment by jessegreenberg** [comment]
> issue identified in #45 (comment) is resolved

Done with the above commit.

@samreid pointed out that this
> May be annoying if the user set up a track which looks like it is above ground or just touches the ground but actually numerically has some sample points below ground.

This will only ever happen while the user is dragging control points. On release, the track is bumped above ground so this will never happen when the user has a track fully set up for play. This assertion hasn't been hit since https://github.com/phetsims/energy-skate-park/commit/da722dda4097d77aec2a8d863b0e3467edbc9d78 so I think this can be closed.

**Comment by jessegreenberg** [comment]
I hit this again doing local fuzz testing
> "Assertion failed: Thermal energy should be non-negative: skaterState: [object Object], oldPotentialEnergy:-816.5615257203782, skaterPositionY:-1.1508080948633031e-7, initialEnergy: -816.5615257203782, proposedPosition: Vector2(-3.310265562725696, 0), proposedVelocity: Vector2(1.8369689821563303e-17, -0.05), dt: 0.016666666666666666, newSpeed: 1.8369689821563303e-17, newKineticEnergy: 7.086355586949376e-33, newPotentialEnergy: -816.5615112201962, newThermalEnergy: -0.00001450018203286163, referenceHeight: 6.480646914446002, tracked in https://github.com/phetsims/energy-skate-park/issues/45"

**Comment by jessegreenberg** [comment]
Wait, is this related to #44 then? Here is the current code that attempts to conserve energy in #44
```js
        let newThermalEnergy = initialEnergy - newKineticEnergy - newPotentialEnergy;

        // Sometimes (depending on dt) the thermal energy can go negative by the above calculation, see #141
        // In that case, set the thermal energy to zero and reduce the speed to compensate.
        if ( newThermalEnergy < skaterState.thermalEnergy ) {
          newThermalEnergy = skaterState.thermalEnergy;
          newKineticEnergy = initialEnergy - newPotentialEnergy - newThermalEnergy;

          // if newPotentialEnergy ~= but slightly larger than initialEnergy (since the skater may have been bumped
          // up to the track after crossing) we must accept the increase in total energy, but it should be small
          // enough that the user does not notice it, see https://github.com/phetsims/energy-skate-park/issues/44
          if ( newKineticEnergy < 0 ) {
            newKineticEnergy = 0;

            const newTotalEnergy = newThermalEnergy + newKineticEnergy + newPotentialEnergy;
            assert && assert( Util.equalsEpsilon( newTotalEnergy, initialEnergy, 1E-8 ), 'substantial total energy change after corrections' );
          }

          // ke = 1/2 m v v
          newSpeed = Math.sqrt( 2 * newKineticEnergy / skaterState.mass );
          newVelocity = segment.times( newSpeed );
        }
```

And in switchToGround we have '
```js
      // TODO: This is likely related to issue identified in #45
      const newThermalEnergy = initialEnergy - newKineticEnergy - newPotentialEnergy;
```

So perhaps it is possible that under certain dt (or when potentialEnergy ~= totalEnergy like in #44!) we need to apply this same correction.

**Comment by jessegreenberg** [comment]
This appeared on CT again with
>energy-skate-park-basics : xss-fuzz : run
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: Thermal energy should be non-negative: skaterState: [object Object], oldPotentialEnergy:-0.0002012054320273447, skaterPositionY:-3.2849866453444034e-7, initialEnergy: -0.0002012054320273447, proposedPosition: Vector2(-6.385311486205166, 0), proposedVelocity: Vector2(1.0001228170926217e-17, -0.16333333333333333), dt: 0.016666666666666666, newSpeed: 1.0001228170926217e-17, newKineticEnergy: 3.125767653966505e-33, newPotentialEnergy: 0, newThermalEnergy: -0.0002012054320273447, referenceHeight: 0, tracked in https://github.com/phetsims/energy-skate-park/issues/45

Again, see how potential energy is ~= to total energy.

**Comment by jessegreenberg** [comment]
I generalized https://github.com/phetsims/energy-skate-park/issues/45#issuecomment-566341820 so that this similar correction can be used both in `interactWithTracksWhileFalling` and `switchToGround`. Ill be watching CT.

**Comment by jessegreenberg** [comment]
Looks like we still hit this:

```
energy-skate-park : xss-fuzz : run
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: substantial total energy change after corrections
Error: Assertion failed: substantial total energy change after corrections
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1576822666409/assert/js/assert.js?bust=1576831138659:22:13)
    at LabModel.correctThermalEnergy (https://bayes.colorado.edu/continuous-testing/snapshot-1576822666409/energy-skate-park/js/energy-skate-park/common/model/EnergySkateParkModel.js?bust=1576831138742:611:17)
    at LabModel.interactWithTracksWhileFalling (https://bayes.colorado.edu/continuous-testing/snapshot-1576822666409/energy-skate-park/js/energy-skate-park/common/model/EnergySkateParkModel.js?bust=1576831138742:782:39)
    at LabModel.stepFreeFall (https://bayes.colorado.edu/continuous-testing/snapshot-1576822666409/energy-skate-park/js/energy-skate-park/common/model/EnergySkateParkModel.js?bust=1576831138742:643:23)
    at LabModel.stepModel (https://bayes.colorado.edu/continuous-testing/snapshot-1576822666409/energy-skate-park/js/energy-skate-park/common/model/EnergySkateParkModel.js?bust=1576831138742:1423:69)
    at LabModel.step (https://bayes.colorado.edu/continuous-testing/snapshot-1576822666409/energy-skate-park/js/energy-skate-park/common/model/EnergySkateParkModel.js?bust=1576831138742:427:31)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1576822666409/joist/js/Sim.js?bust=1576831138742:228:22
    at Action.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1576822666409/axon/js/Action.js?bust=1576831138742:230:20)
    at EnergySkateParkSim.stepSimulation (https://bayes.colorado.edu/continuous-testing/snapshot-1576822666409/joist/js/Sim.js?bust=1576831138742:971:33)
    at EnergySkateParkSim.stepOneFrame (https://bayes.colorado.edu/continuous-testing/snapshot-1576822666409/joist/js/Sim.js?bust=1576831138742:952:14)
id: Bayes Chrome
Approximately 12/20/2019, 1:17:46 AM
```

**Comment by jessegreenberg** [comment]
I think I tracked it down again - error in `correctThermalEnergy` where the new position wasn't applied to the corrected skater state and so potential energy was incorrect after correction. Fixed above but ill be watching.

**Comment by jessegreenberg** [comment]
We have had 10 CT iterations since commit without error. I think this issue can now be closed. At this point we are finding and closing new issues related to this classification of issue which is "substantial total energy change after ... correction". And so if it shows up again I feel comfortable proceeding in a new issue.
