### ISSUE TITLE
CT: iframe api failed

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/energy-skate-park#50]
```
energy-skate-park : phet-io-tests : no-assert
6 out of 7 tests passed. 1 failed.
SimTests: energy-skate-park: iframe api failed:
instance metadata should match for energySkatePark.measureScreen.measureScreenView.controlPanel
    at Object.callback (https://bayes.colorado.edu/continuous-testing/snapshot-1546530276509/phet-io-wrappers/js/tests/SimTests.js?bust=1546533022225:344:22)
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1546530276509/phet-io-wrappers/common/js/Client.js:311:83)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1546530276509/phet-io-wrappers/common/js/Client.js:348:15)


id: Bayes Chrome
Approximately 1/3/2019, 8:44:36 AM
```

**Comment by samreid** [comment]
![image](https://user-images.githubusercontent.com/679486/51042501-ba293680-1579-11e9-8ec1-f81bc739b293.png)

**Comment by samreid** [comment]
To be clear, it expected the EnergySkateParkControlPanel to have phetioEventType `model` but it is coming up as `user`.

**Comment by samreid** [comment]
I committed the proposed fix and it is passing in local testing.  The EnergySkateParkVisibilityControls was introduced in ab8c037dcfc39d80773063c9d7ac0cf777a3f353 but `tandem.createTandem` was not used. Since this simulation is instrumented for PhET-iO, it seems valuable to run the "Wrapper Unit Tests" link from phetmarks either (a) before committing or (b) once a day or (c) to carefully monitor Bayes CT to catch issues like this as they are introduced.

@jessegreenberg can you please review?

**Comment by jessegreenberg** [comment]
> Since this simulation is instrumented for PhET-iO, it seems valuable to run the "Wrapper Unit Tests" link from phetmarks either (a) before committing 

OK, sounds good, Ill do this moving forward.

**Comment by samreid** [comment]
Thanks!  In the preceding commit, I added some other missing tandems that were caught by the Wrapper Unit Tests.  Still investigating the "Cannot read property 'createAnotherDiv' of undefined", but I'll do that in another issue.  Leaving assigned to @jessegreenberg to double check my commit above, if that seems well, this issue can be closed.

**Comment by jessegreenberg** [comment]
All looks great for this issue and "Wrapper unit tests" are passing. Closing.
